language: node_js
node_js:
- '9'
deploy:
  provider: heroku
  api_key:
    secure: lJFOGfR1A+Ayde7X3ePOKCqC8LIlsJmMIuw8uRKzbzSjst7N07eGBfCpkzPKV8/A+FPfLwqiIeXFxZNlVC+W/9cplRAqtgTH9v4C0pg8Bk2At+lcex7QN1xqOIbiWdW/V6ZmVcGsrlew2Lfi13fYxre8+uCjBJ9wMX9y6YAPgpx2Joz1zq52O6lPLZ+v4dU65jg+UWlj+S1eFfkTCjd3hkMDDndAz4ItOl9rW2UUna8yfAKFOEBCWQRMrc/rtykAHNU7JPhcq19Zh1ADEjkxdF2V5tsMdDpQ15kCM+RzKEp+KiAX2KRwbUgU4BTgTXCsRHQ0stJBe13JF0dPQlN70B7wg1V3QAlp26VCwYPl54oyBB152xGSNZM7RWwr8IT+Sw/CmMqi1YCVsXTjJLwSBvSskra4RQDX1kBnomy0c6P7oxnAdCWloncVSwOrWdGXO8aMbFodqNjD2CKWisypBEL+zZc1gfFfGXLEwDOpOfvwCJ//CykVBNFHa0FXdG4cxTRp6TAVjFKgiomiLXeAV3R67eqboTsfPvpZV/0iLROKfnQXpTfVbp10Q7YW/4/+oWzNXuYhgr222aqI53q8n6Yq5VMl5ZVQuUlMnCeXGOUjN/qmZqau+HwblOaSrl6t7MuE/oxOOSYGPIHkkJJnUJ2t3A+tD+fDlkfPIbC8hk8=
  app: safe-eyrie-53222
  on:
    repo: vjrasane/fullstackopen7
